before_script:
  - apt update -qq
  - apt install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_production:
  type: deploy
  environment:
    name: production
    url: alterigor.ai
  script:
    - ssh enzjr8j6ydyn@alterigor.ai "cd public_html/alterigor-webgl && git checkout master && git pull origin master && exit"
  only:
    - master